# ┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
# ┃                     ⭐ NVanish v1.3 ⭐                       ┃
# ┃                Плагин для скрытия игроков                   ┃
# ┃              Разработчик: ✦ noloverme ✦                    ┃
# ┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┛

# ⚙️ Версия конфигурации
# Не изменяйте эту строку!
config_version: 1.3

# 📊 Настройки хранилища данных
database:
  type: JSON  # MySQL или JSON, если не удалось подключиться к MySQL то используется JSON
  MYSQL:
    host: localhost
    port: 3306
    database: nvanish
    user: "root"
    password: "psw"
  JSON:
    location: plugins/NVanish/database

# 💬 Сообщения плагина 
# Поддерживаются цветовые коды и форматирование:
# • Стандартные коды: &a, &b, §c и т.д.
# • HEX-цвета: &#FFFFFF, &x&F&F&F&F&F&F, §x§F§F§F§F§F§F
# • Можно использовать эмодзи и юникод
# • Используйте %prefix% для вставки префикса плагина
messages:
  # 🏷️ Системный префикс плагина
  # Используется во всех системных сообщениях
  prefix: "&#00FFFF&l[NVanish] &#FFFFFF"

  # 🔒 Основные сообщения
  no_permission: "%prefix%&#FF5555❌ Недостаточно прав для выполнения этой команды."
  no_player: "%prefix%&#FF5555❌ Игрок не найден! Проверьте правильность введённого ника."
  help: |-  # /vanish
    &#FFD700✧ &#FFFF00NVanish &#FFFFFFпомощь:
     &#FF6347/%cmd% &#FFFFFF- %desc%
     &#FF6347/%cmd% on &#FFFFFF- 🔍 Включить невидимость
     &#FF6347/%cmd% off &#FFFFFF- 👁️ Выключить невидимость
     &#FF6347/%cmd% on [игрок] &#FFFFFF- 🔍 Включить невидимость игроку
     &#FF6347/%cmd% off [игрок] &#FFFFFF- 👁️ Выключить невидимость игроку
     &#FF6347/%cmd% reload &#FFFFFF- 🔄 Перезагрузить плагин
  
  # 👻 Сообщения о включении/выключении невидимости
  vanish_enabled: "%prefix%&#00FF7F✅ Режим невидимости &#00FFFF👻 активирован! Обычные игроки вас не видят."
  vanish_disabled: "%prefix%&#00FF7F✅ Режим невидимости &#FF6347❌ деактивирован! Теперь вас видят все."
  vanish_enabled_other: "%prefix%&#00FF7F✅ Игрок &#FFFFFF%player% &#00FF7F теперь невидим для обычных игроков!"
  vanish_disabled_other: "%prefix%&#00FF7F✅ Игрок &#FFFFFF%player% &#00FF7F снова видим для всех игроков!"
  
  # 🔄 Системные сообщения
  plugin_reloaded: "%prefix%&#00FF7F✅ Плагин успешно перезагружен!"
  join_vanished: "%prefix%&#00FFFF👻 Вы вошли в режиме невидимости! Обычные игроки вас не видят."
  chat_blocked: "%prefix%&#FF5555❌ В режиме невидимости писать в чат нельзя!"
  item_drop_blocked: "%prefix%&#FF5555❌ В режиме невидимости выбрасывать предметы нельзя!"
  player_only: "%prefix%&#FF5555❌ Эта команда доступна только для игроков!"
  
  # 🔌 Сообщения интеграций и ошибок
  placeholder_api_found: "%prefix%&#00FF7F✅ Обнаружен PlaceholderAPI! Поддержка placeholder'ов активирована."
  placeholder_api_not_found: "%prefix%&#FFD700⚠️ PlaceholderAPI не найден. Поддержка placeholder'ов отключена."
  placeholder_error: "%prefix%&#FF5555❌ Ошибка при обработке placeholders: %error%"
  placeholder:
    vanished: "&#FF0000&l👻 Скрыт"   # Текст для плейсхолдера %nvanish_status_text%, когда игрок скрыт
    visible: "&#00FF00&l👁️ Виден"    # Текст для плейсхолдера %nvanish_status_text%, когда игрок виден
  plugin_enabled: "%prefix%&#00FF7F✅ Плагин NVanish v%version% успешно загружен!"
  plugin_disabled: "%prefix%&#FF6347❌ Плагин NVanish выключен."
  plugin_reloaded_log: "%prefix%&#00FF7F✅ Плагин NVanish успешно перезагружен!"
  storage_error: "%prefix%&#FF5555❌ Не удалось инициализировать хранилище данных!"
  storage_reload_error: "%prefix%&#FF5555❌ Ошибка при перезагрузке хранилища данных!"
  
  # 🔄 Сообщения об обновлении конфигурации
  config_outdated: "%prefix%&#FFD700⚠️ Обнаружена устаревшая версия конфигурации (%current% -> %latest%)! Используйте /vanish reload для обновления."
  config_updated: "%prefix%&#00FF7F✅ Конфигурация успешно обновлена до версии %version%! Резервная копия сохранена в %backup%."
  config_backup_failed: "%prefix%&#FF5555❌ Не удалось создать резервную копию конфигурации!"
  
  # 🚨 Сообщения системы отчетов
  report_usage: "%prefix%&#FFFF00Использование: /%cmd% <bug|suggestion|other> <текст отчета>"
  report_sent: "%prefix%&#00FF7F✅ Ваш отчет успешно отправлен! Спасибо за помощь в улучшении плагина."
  report_failed: "%prefix%&#FF5555❌ Не удалось отправить отчет. Пожалуйста, попробуйте позже."
  report_cooldown: "%prefix%&#FFD700⚠️ Вы сможете отправить следующий отчет через %time% секунд."
  invalid_report_category: "%prefix%&#FF5555❌ Недопустимая категория отчета. Используйте: bug, suggestion или other."
  new_report: "%prefix%&#FFD700⚠️ Получен новый отчет от игрока &#FFFFFF%player% &#FFD700(категория: &#FFFFFF%category%&#FFD700, ID: &#FFFFFF%id%&#FFD700)"

# 🛡️ Ограничения для игроков в ванише
restrictions:
  disable_chat: false           # 💬 Отключить чат
  disable_block_interaction: false  # 🧱 Отключить взаимодействие с блоками
  disable_damage: false         # ⚔️ Отключить нанесение урона
  invulnerable: true           # 🛡️ Неуязвимость
  disable_hunger: true         # 🍖 Отключить голод
  disable_item_pickup: false    # 📥 Отключить подбор предметов
  disable_item_drop: false      # 📤 Отключить выбрасывание предметов

# 📢 Настройки скрытия сообщений
hide_messages:
  enabled: true               # 🔄 Включить/выключить скрытие сообщений для игроков в ванише
  join_messages: true         # 📥 Скрывать сообщения о входе на сервер
  quit_messages: true         # 📤 Скрывать сообщения о выходе с сервера
  death_messages: true        # ☠️ Скрывать сообщения о смерти

# ✨ Эффекты для игроков в ванише
effects:
  flight: true                # 🕊️ Полет в ванише
  night_vision: true          # 🌙 Ночное зрение в ванише

# 🎮 Игровой режим при ванише
# Доступные режимы: survival, creative, adventure, spectator
# Оставьте пустым для сохранения текущего режима игрока
vanish_gamemode: ""

# 📋 Настройки ActionBar уведомления в ванише
actionbar:
  enabled: true                  # 🔄 Включить/выключить ActionBar уведомление
  message: "&#FF0000&l👻 &#FFFFFFВы находитесь в режиме &#FF0000&lваниша!"  # 💬 Сообщение в ActionBar (поддерживает %prefix%)
  update_interval: 20            # ⏱️ Интервал обновления в тиках (20 тиков = 1 секунда)
  
# 🔌 Интеграция с PlaceholderAPI
placeholders:
  enabled: true                  # 🔄 Включить/выключить поддержку PlaceholderAPI
  
  # Доступные плейсхолдеры:
  # %nvanish_status% - возвращает статус ваниша игрока (true/false)
  # %nvanish_status_text% - возвращает статус ваниша игрока (Скрыт/Виден)
  # %nvanish_count% - возвращает количество скрытых игроков
  # %nvanish_can_see_<player>% - может ли текущий игрок видеть указанного
  # %nvanish_list% - список скрытых игроков через запятую
  # %nvanish_visible_count% - количество видимых игроков (не в ванише)

# 🎙️ Интеграция с голосовыми чатами
voice_chat:
  plasmo_voice:
    enabled: false               # 🔄 Включить/выключить интеграцию с PlasmoVoice
    hide_voice: true             # 🔇 Скрывать ли звук от скрытого игрока
    block_hearing: false         # 👂 Блокировать ли возможность слышать других игроков
  simple_voice:
    enabled: false               # 🔄 Включить/выключить интеграцию с SimpleVoice
    hide_voice: true             # 🔇 Скрывать ли звук от скрытого игрока

# 📝 Настройки журнала действий
logging:
  enabled: true                  # 🔄 Включить/выключить ведение журнала действий
  to_console: true               # 🖥️ Выводить логи в консоль сервера
  to_file: true                  # 📄 Сохранять логи в файл

# 🚨 Настройки системы отчетов
reports:
  enabled: false                  # 🔄 Включить/выключить систему отчетов
  notify_admins: true            # 📢 Уведомлять администраторов о новых отчетах
  cooldown: 300                  # ⏱️ Время ожидания между отправкой отчетов (в секундах)
