name: NVanish
main: com.noloverme.nvanish.NVanish
version: "${project.version}"
api-version: 1.21
authors: [noloverme]
depend: [ProtocolLib, PlasmoVoice]
softdepend: [PlaceholderAPI]
description: Мощный плагин для режима невидимки.

commands:
  vanish:
    description: Включает или выключает режим невидимки.
    usage: /<command>
    permission: nvanish.use
    aliases:
      - v
      - nvanish
permissions:
  nvanish.use:
    description: Позволяет игроку использовать команду /vanish.
    default: op
  nvanish.use_others:
    description: Позволяет игроку использовать /vanish на других игроках.
    default: op
  nvanish.see_vanished:
    description: Позволяет игроку видеть тех, кто находится в режиме невидимки.
    default: op
  nvanish.bypass.gamemode:
    description: Позволяет игроку обходить ограничение на смену игрового режима.
    default: op
  nvanish.bypass.hit:
    description: Позволяет игроку атаковать, находясь в режиме невидимки.
    default: op
  nvanish.bypass.interact:
    description: Позволяет игроку взаимодействовать, находясь в режиме невидимки.
    default: op
