settings:
  set_gamemode: true #включает гм 3 #nvanish.bypass.gamemode
  disable_on_hit: true #nvanish.bypass.hit
  disable_on_interact: true #nvanish.bypass.interact
  silent_join_quit: true
  mob_invisible: true
  actionbar_enabled: true

messages:
  no_permission: "&cУ вас нет прав для выполнения этой команды!"
  vanish_on: "&7Вы вошли в режим невидимки."
  vanish_off: "&7Вы вышли из режима невидимки."
  vanish_other_on: "&7Игрок &e%player% &7вошел в режим невидимки."
  vanish_other_off: "&7Игрок &e%player% &7вышел из режима невидимки."
  player_not_found: "&cИгрок не найден."
  only_players: "&cТолько игрок может использовать эту команду."
  action_blocked: "&cВаше действие было заблокировано, пока вы в режиме невидимки."
  vanished_list_header: "&7Список невидимых игроков (%count%):"
  vanished_list_entry: "&7- &e%player%"
  config_reloaded: "&aКонфигурация плагина перезагружена."
  actionbar_message: "&cВы невидимы!&r"